### ISSUE TITLE
How to css the Web3Modal

### ISSUE THREAD

**Issue by venkateshsys** [WalletConnect/web3modal#226]
Styling all providers in this format

![image](https://user-images.githubusercontent.com/48546261/103738669-68a5cc00-501a-11eb-8057-c1c0f9735dc3.png)

**Comment by pedrouid** [comment]
I believe this an app style... I'm not sure how this relates to Web3Modal

**Comment by Candy-u** [comment]
Hello, has the problem been solved？

**Comment by fatihmert** [comment]
Maybe you can change css style like this result following;

![webmodal-custom-css](https://i.hizliresim.com/8o1f8me.png)

```css
.web3modal-modal-card{
    width: 400px!important;
    min-width: unset!important;
    max-width: unset!important;
}

.web3modal-provider-container{
    flex-direction: row!important;
}

.web3modal-provider-description{
    display:none;
}
```
